[serve]
# The address to serve on LAN.
# address = "127.0.0.1"
# The address to serve on WAN.
address = "0.0.0.0"

# The port to serve on.
port = 8080

[[hooks]]
stage = "pre_build"
command = "clear"

[[hooks]]
stage = "pre_build"
command = "npm"
command_arguments = ["run", "build:css"]
